### ISSUE TITLE
实在是太多人不会用了，我决定录个视频

### ISSUE THREAD

**Issue by aoaostar** [aoaostar/mooc#10]
决定录个视频发B站，谁借个号给我？？？  
2023年4月26日录制

**Comment by 52qkm** [comment]
> 
我可以

**Comment by 52qkm** [comment]
![image](https://user-images.githubusercontent.com/131792889/234331202-7de1d6eb-29fa-4757-b780-135757c1fc79.png)

**Comment by aoaostar** [comment]
> > 
> 
> 我可以

好，来吧

**Comment by SHADY1014** [comment]
![image](https://user-images.githubusercontent.com/93665187/234455898-2895d241-9ee4-4960-a8cd-9959a8ca0f45.png)
配置好脚本我也是这样

**Comment by SHADY1014** [comment]
![Uploading image.png…]()
又可以了，不知道是不是开了代理的原因

**Comment by SHADY1014** [comment]
![image](https://user-images.githubusercontent.com/93665187/234457920-4655b35a-c0bd-44ad-a214-1b15f74fa84e.png)
我可以啊

**Comment by lmx20030509** [comment]
> 
还需要号吗作者大大

**Comment by lmx20030509** [comment]
> 决定录个视频发B站，谁借个号给我??? 2023年4月26日录制

是需要b站号吗

**Comment by aoaostar** [comment]
> > 决定录个视频发B站，谁借个号给我??? 2023年4月26日录制
> 
> 是需要b站号吗

视频已经录完发布了，不需要了，谢谢
