### ISSUE TITLE
运行一段时间后，爆错：  fatal error: concurrent map writes 是什么原因呢

### ISSUE THREAD

**Issue by zhanggx123** [aoaostar/mooc#3]
![image](https://user-images.githubusercontent.com/60429093/204464049-d94a344b-086e-4be9-87aa-4075ddb8f0c2.png)

**Comment by aoaostar** [comment]
版本号多少？
最新版本应该是修复了的#2

**Comment by zhanggx123** [comment]
> 版本号多少？ 最新版本应该是修复了的#2

v1.3

**Comment by aoaostar** [comment]
> > 版本号多少？ 最新版本应该是修复了的#2
> 
> v1.3

最新版v1.3.1

**Comment by zhanggx123** [comment]
> > > 版本号多少？ 最新版本应该是修复了的#2
> > 
> > 
> > v1.3
> 
> 最新版v1.3.1

我看日志 好像给出的是 请求 这个接口出现的问题 /api/node/study.json，提交学时那一块

**Comment by zhanggx123** [comment]
> > > 版本号多少？ 最新版本应该是修复了的#2
> > 
> > 
> > v1.3
> 
> 最新版v1.3.1

好的，谢谢大佬
