### ISSUE TITLE
你好大佬

### ISSUE THREAD

**Issue by ziqilin12** [aoaostar/mooc#4]
配置完黑框显示选择学校信息怎么搞，能不能出个小白的教程

**Comment by moyulengtu** [comment]
我也是个小白，请问你的怎么配置那个json文件的

**Comment by aoaostar** [comment]
![image](https://user-images.githubusercontent.com/86001674/228408996-544a9760-e43c-40e0-b0d4-4a39bb19a9df.png)
这不是写的很清楚了？

**Comment by moyulengtu** [comment]
噢噢 好的 抱歉大佬 我太白了 对不起对不起😭我再研究研究



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月29日(周三) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [aoaostar/mooc] 你好大佬 (Issue #4)




 

 这不是写的很清楚了？
