### ISSUE TITLE
客户端1.3.2运行失败

### ISSUE THREAD

**Issue by yang-sir-one** [aoaostar/mooc#7]
您好，我使用的1.3.2版本的客户端，config文件配置好之后，双击运行后一直无显示，使用管理员打开报错aoaostar_mooc.exe文件无法运行，如下图
![image](https://user-images.githubusercontent.com/81810124/231403983-2cec65f0-a0f3-4f47-927a-5599dfb1fa85.png)
![image](https://user-images.githubusercontent.com/81810124/231404311-90d81103-6aef-4d64-8af3-e427ec4e6dec.png)

**Comment by aoaostar** [comment]
双击运行后，反应慢就等
