### ISSUE TITLE
大佬帮帮

### ISSUE THREAD

**Issue by 3490175200** [aoaostar/mooc#8]
![QQ截图20230424230346](https://user-images.githubusercontent.com/131689967/234040047-de8bb16a-3f62-423e-bcc2-c168353795b9.png)
不是这样配置的吗，，，，我太小白了，，help！！！！1

**Comment by aoaostar** [comment]
你可真是个小机灵鬼，school_id我给的示例是数字，翻译成中文就是学校id
你为什么会把网址填那里呢？
上面有个网址你照葫芦画瓢替换一下不就行了吗？
而且我给的base_url示例是https://xxx.com
你就按照格式填写网址啊，末尾的 user/login就删掉啊

**Comment by CodingJing** [comment]
> ![QQ截图20230424230346](https://user-images.githubusercontent.com/131689967/234040047-de8bb16a-3f62-423e-bcc2-c168353795b9.png) 不是这样配置的吗，，，，我太小白了，，help！！！！1
笨蛋 真给襄阳人丢脸..

**Comment by aoaostar** [comment]
> ![QQ截图20230424230346](https://user-images.githubusercontent.com/131689967/234040047-de8bb16a-3f62-423e-bcc2-c168353795b9.png) 不是这样配置的吗，，，，我太小白了，，help！！！！1
> 笨蛋 真给襄阳人丢脸..

照着视频来
